# Generated by Django 4.2.7 on 2023-11-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_service_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_package_id', to='packages.package'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_master_id', to='packages.servicemaster'),
        ),
    ]
