# Generated by Django 4.2.7 on 2023-12-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_service_end_date_remove_service_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('package', 'package'), ('service', 'service')], default='service', max_length=50),
        ),
    ]
