# Generated by Django 4.2.7 on 2023-12-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_remove_package_currency_remove_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='platform_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='platform_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
