# Generated by Django 4.2.7 on 2023-12-28 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_remove_service_is_duration_based_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMasterMetaData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ServiceMasterMetaData')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('min', models.CharField(blank=True, max_length=100, null=True)),
                ('max', models.CharField(blank=True, max_length=100, null=True)),
                ('span', models.IntegerField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('text', 'text'), ('long_text', 'long_text'), ('date_time', 'date_time'), ('media', 'media')], default='text', max_length=50)),
                ('service_master_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_master_meta_data_id', to='packages.servicemaster')),
            ],
            options={
                'db_table': 'service_master_meta_data',
            },
        ),
    ]
