# Generated by Django 4.2.7 on 2024-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_servicemastermetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemastermetadata',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
