# Generated by Django 4.2.7 on 2024-02-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_servicemastermetadata_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemastermetadata',
            name='field_name',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('tweet_id', 'tweet_id'), ('in_reply_to_tweet_id', 'in_reply_to_tweet_id'), ('poll_options', 'poll_options'), ('poll_duration_minutes', 'poll_duration_minutes')], max_length=50, null=True),
        ),
    ]
