# Generated by Django 4.2.7 on 2024-02-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_alter_servicemaster_twitter_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemastermetadata',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('long_text', 'long_text'), ('date_time', 'date_time'), ('media', 'media'), ('array', 'array')], default='text', max_length=50),
        ),
    ]
