# Generated by Django 4.2.7 on 2024-04-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0015_alter_servicemastermetadata_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="platform_fees",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
    ]
