# Generated by Django 4.2.7 on 2024-04-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0016_alter_service_platform_fees_alter_service_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemaster",
            name="twitter_service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tweet", "tweet"),
                    ("like_tweet", "like_tweet"),
                    ("reply_to_tweet", "reply_to_tweet"),
                    ("quote_tweet", "quote_tweet"),
                    ("poll", "poll"),
                    ("retweet", "retweet"),
                    ("thread", "thread"),
                    ("spaces", "spaces"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
