# Generated by Django 4.2.7 on 2024-02-22 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_currency_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRewardsMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='User Referral Rewards ID')),
                ('type', models.CharField(choices=[('comission', 'comission'), ('discount', 'discount')], default='service', max_length=50)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referral_rewards_master',
            },
        ),
        migrations.CreateModel(
            name='UserReferrals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='User Referral ID')),
                ('referred_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by_account', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_user_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_referrals',
            },
        ),
        migrations.CreateModel(
            name='UserReferralRewards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='User Referral Rewards ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('is_claimed', models.BooleanField(blank=True, default=False, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_bank_account_currency', to='core.currency')),
                ('type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_referral_referral_master_type', to='referrals.referralrewardsmaster')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_user_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_referrals_rewards',
            },
        ),
    ]
