# Generated by Django 4.2.7 on 2023-12-08 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Order')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_buyer_id', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_currency_id', to='core.currency')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_package_id', to='packages.package')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='OrderItem')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_currency_id', to='core.currency')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_order_id', to='orders.order')),
                ('service_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_service_master_id', to='packages.servicemaster')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='OrderMessage')),
                ('status', models.CharField(blank=True, choices=[('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read')], max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_message_order_id', to='orders.order')),
                ('receiver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_id', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_message',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Transactions')),
                ('transaction_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('debit', 'debit'), ('credit', 'credit')], max_length=50, null=True)),
                ('transaction_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('refunded', 'refunded'), ('processing', 'processing')], max_length=50, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_currency_id', to='core.currency')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tranaction_order_id', to='orders.order')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Review')),
                ('note', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_order_id', to='orders.order')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='OrderMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='OrderMessageAttachment')),
                ('filename', models.TextField(blank=True, null=True)),
                ('order_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_message_id', to='orders.ordermessage')),
            ],
            options={
                'db_table': 'order_message_attachment',
            },
        ),
        migrations.CreateModel(
            name='OrderItemTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='OrderItemTracking')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_id', to='orders.orderitem')),
            ],
            options={
                'db_table': 'order_item_tracking',
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='OrderAttachment')),
                ('filename', models.TextField(blank=True, null=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_attachment_order_id', to='orders.order')),
            ],
            options={
                'db_table': 'order_attachment',
            },
        ),
    ]
