# Generated by Django 4.2.7 on 2024-01-08 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_languagemaster_delete_language'),
        ('packages', '0008_servicemastermetadata'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemMetaData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ServiceMasterMetaData')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('min', models.CharField(blank=True, max_length=100, null=True)),
                ('max', models.CharField(blank=True, max_length=100, null=True)),
                ('span', models.IntegerField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('text', 'text'), ('long_text', 'long_text'), ('date_time', 'date_time'), ('media', 'media')], default='text', max_length=50)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_item_meta_data',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='package',
        ),
        migrations.RemoveField(
            model_name='orderattachment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderattachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderattachment',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_attachment_order_item_id', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_package_id', to='packages.package'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_currency_id', to='core.currency'),
        ),
    ]
