# Generated by Django 4.2.7 on 2024-01-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitemmetadata_remove_order_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmetadata',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='orderitemmetadata',
            name='max',
        ),
        migrations.RemoveField(
            model_name='orderitemmetadata',
            name='min',
        ),
        migrations.RemoveField(
            model_name='orderitemmetadata',
            name='placeholder',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('completed', 'completed')], default='draft', max_length=50),
        ),
    ]
