# Generated by Django 4.2.7 on 2024-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
