# Generated by Django 4.2.7 on 2024-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitemmetadata_max_orderitemmetadata_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmetadata',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
