# Generated by Django 4.2.7 on 2024-01-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitemmetadata_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermessage',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read')], default='sent', max_length=50),
        ),
    ]
