# Generated by Django 4.2.7 on 2024-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_publish_date_orderitem_published_tweet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('cancelled', 'cancelled'), ('rejected', 'rejected'), ('finalized', 'finalized'), ('scheduled', 'scheduled'), ('published', 'published')], default='in_progress', max_length=50),
        ),
    ]
