# Generated by Django 4.2.7 on 2024-01-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderitem_celery_task_id_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('cancelled', 'cancelled'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('scheduled', 'scheduled'), ('published', 'published')], default='in_progress', max_length=50),
        ),
    ]
