# Generated by Django 4.2.7 on 2024-02-02 10:37

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20240202_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=orders.models.generate_order_number, unique=True),
        ),
    ]
