# Generated by Django 4.2.7 on 2024-02-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_transaction_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='influencer_transaction_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
