# Generated by Django 4.2.7 on 2024-02-06 10:05

from django.db import migrations


def create_transaction_type(apps, schema_editor):
    Transaction = apps.get_model('orders', 'Transaction')
    User = apps.get_model('accounts', 'User')

    for transaction in Transaction.objects.all():
        user = User.objects.get(id=transaction.transaction_initiated_by.id)
        if user.role.name == "influencer":
            transaction.transaction_type = "claim_escrow"
        else:
            transaction.transaction_type = "initiate_escrow"
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_transaction_transaction_type'),
    ]

    operations = [
        migrations.RunPython(create_transaction_type),
    ]
