# Generated by Django 4.2.7 on 2024-02-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20240206_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_transaction_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='influencer_transaction_address',
        ),
    ]
