# Generated by Django 4.2.7 on 2024-02-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_order_buyer_transaction_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmetadata',
            name='regex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
