# Generated by Django 4.2.7 on 2024-02-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='is_system_message',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
