# Generated by Django 4.2.7 on 2024-03-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_ordermessage_is_system_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
