# Generated by Django 4.2.7 on 2024-03-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_orderitem_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
