# Generated by Django 4.2.7 on 2024-03-13 06:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0035_escrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnChainTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="OnChainTransaction",
                    ),
                ),
                ("slot", models.BigIntegerField(blank=True, null=True)),
                ("confirmations", models.BigIntegerField(blank=True, null=True)),
                ("err", models.JSONField(blank=True, null=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("processed", "processed"),
                            ("confirmed", "confirmed"),
                            ("finalized", "finalized"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cancel_escrow", "cancel_escrow"),
                            ("confirm_escrow", "confirm_escrow"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_confirmed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "escrow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="on_chain_transaction_escrow_id",
                        to="orders.escrow",
                    ),
                ),
            ],
            options={
                "db_table": "on_chain_transaction",
            },
        ),
    ]
