# Generated by Django 4.2.7 on 2024-03-13 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0036_onchaintransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItemMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="OrderItemMetric",
                    ),
                ),
                ("metric", models.CharField(blank=True, max_length=100, null=True)),
                ("value", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item_metric_order_item_id",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "db_table": "order_item_metric",
            },
        ),
    ]
