# Generated by Django 4.2.7 on 2024-03-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0038_alter_orderitemmetric_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="approved",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
