# Generated by Django 4.2.7 on 2023-12-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
