# Generated by Django 4.2.7 on 2023-11-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='accessToken',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
