# Generated by Django 4.2.7 on 2023-11-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_twitteraccount_accesstoken_twitteraccount_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteraccount',
            old_name='accessToken',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='twitteraccount',
            old_name='userName',
            new_name='user_name',
        ),
    ]
