# Generated by Django 4.2.7 on 2023-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accesstoken_twitteraccount_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
