# Generated by Django 4.2.7 on 2023-11-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_twitter_account'),
        ('accounts', '0004_alter_twitteraccount_access_token_and_more'),
    ]

    operations = [
    ]
