# Generated by Django 4.2.7 on 2023-12-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_username'),
        ('accounts', '0004_twitteraccount_joined_at_twitteraccount_location_and_more'),
    ]

    operations = [
    ]
