# Generated by Django 4.2.7 on 2023-12-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20231128_0707'),
        ('accounts', '0005_merge_20231129_0511'),
    ]

    operations = [
    ]
