# Generated by Django 4.2.7 on 2023-12-26 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_twitteraccount_joined_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Wallet Network ID')),
                ('wallet_network', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletProider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Wallet Provider ID')),
                ('wallet_provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Wallet ID')),
                ('is_primary', models.BooleanField(blank=True, default=True, null=True)),
                ('wallet_address_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_user_id', to=settings.AUTH_USER_MODEL)),
                ('wallet_network_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_network_id', to='accounts.walletnetwork')),
                ('wallet_provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_provider_id', to='accounts.walletproider')),
            ],
        ),
    ]
