# Generated by Django 4.2.7 on 2023-12-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_walletnetwork_walletproider_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletProider',
            new_name='WalletProvider',
        ),
    ]
