# Generated by Django 4.2.7 on 2024-01-02 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_languagemaster_delete_language'),
        ('accounts', '0008_rename_walletproider_walletprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Account Language ID')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_language_master_id', to='core.languagemaster')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_user_account_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_language',
            },
        ),
    ]
