# Generated by Django 4.2.7 on 2024-01-18 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_businessaccountmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccountmetadata',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_business_meta_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
