# Generated by Django 4.2.7 on 2024-01-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_businessaccountmetadata_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccountmetadata',
            name='bio',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
