# Generated by Django 4.2.7 on 2024-01-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_businessaccountmetadata_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccountmetadata',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
