# Generated by Django 4.2.7 on 2024-01-24 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_regionmaster'),
        ('accounts', '0013_alter_businessaccountmetadata_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Account Region ID')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_master_id', to='core.regionmaster')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_user_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_region',
            },
        ),
    ]
