# Generated by Django 4.2.7 on 2024-01-24 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_accountregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountregion',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_user_account', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
