# Generated by Django 4.2.7 on 2024-01-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_accountregion_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
