# Generated by Django 4.2.7 on 2024-01-29 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_accountregion_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountregion',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_user_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
