# Generated by Django 4.2.7 on 2024-01-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_accountregion_user_account'),
        ('accounts', '0016_twitteraccount_refresh_token'),
    ]

    operations = [
    ]
