# Generated by Django 4.2.7 on 2024-02-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_walletnonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='wallet',
        ),
    ]
