# Generated by Django 4.2.7 on 2024-02-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_wallet_deleted_at_alter_wallet_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(blank=True, choices=[('email', 'email'), ('twitter', 'twitter'), ('wallet', 'wallet')], max_length=25, null=True),
        ),
    ]
