# Generated by Django 4.2.7 on 2024-03-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_user_login_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymaster",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="is_verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="show_on_main",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="categorymaster",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("custom", "custom"), ("standard", "standard")],
                max_length=25,
                null=True,
            ),
        ),
    ]
