# Generated by Django 4.2.7 on 2024-02-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_userreferrals_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreferrals',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
