# Generated by Django 4.2.7 on 2024-03-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="promoted_tweet_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
