# Generated by Django 4.2.7 on 2024-02-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_userreferrals_referral_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReferrals',
        ),
    ]
