[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
xfluencer = "EV31JFJxt28CoRUGm2UAsTHndmpYvpuMFH9Y8JZBJcYd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ruben/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
