# Generated by Django 4.2.7 on 2024-01-24 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_currency_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Region Master')),
                ('regionName', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'region_master',
            },
        ),
    ]
