# Generated by Django 4.2.7 on 2024-03-06 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_currency_is_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="HowItWorksRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="How it works route",
                    ),
                ),
                ("route", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "how_it_works_section",
            },
        ),
        migrations.CreateModel(
            name="HowItWorksStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="How it works Step",
                    ),
                ),
                ("step", models.CharField(max_length=100)),
                ("step_label", models.CharField(max_length=255)),
                ("html_content", models.TextField()),
                (
                    "step_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_route",
                        to="core.howitworksroute",
                    ),
                ),
            ],
            options={
                "db_table": "how_it_works_step",
            },
        ),
    ]
