# Generated by Django 4.2.7 on 2024-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_configuration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="country",
        ),
        migrations.AddField(
            model_name="currency",
            name="currency_type",
            field=models.CharField(
                choices=[("SOL", "SOL"), ("SPL", "SPL")], default="SPL"
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="decimals",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="logourl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="token_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
