# Generated by Django 4.2.7 on 2024-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_currency_country_currency_currency_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="network",
            field=models.CharField(
                choices=[
                    ("mainnet", "mainnet"),
                    ("devnet", "devnet"),
                    ("testnet", "testnet"),
                    ("native", "native"),
                ],
                default="native",
            ),
        ),
    ]
