# Generated by Django 4.2.7 on 2024-03-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reward", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rewardconfig",
            name="reward_config_reward_type",
        ),
        migrations.AddField(
            model_name="rewardconfig",
            name="reward_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reward_config_reward_type",
                to="reward.rewardtypes",
            ),
        ),
    ]
