name: Deploy UI

on:
  push:
    branches: [ main ]   
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get Github action IP
      id: ip
      uses: haythem/public-ip@v1.2
    - name: Setting environment variables..
      run: |
        echo "AWS_DEFAULT_REGION=eu-west-2" >> $GITHUB_ENV
        echo "AWS_SG_NAME=${{ secrets.AWS_SECURITY_GROUP_ID }}" >> $GITHUB_ENV
        
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
     
    - name: Steps
      uses: appleboy/ssh-action@master
      continue-on-error: false
      with:
        host: ${{ secrets.DEVSERVER_UI }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SECRETKEY_UI }}
        command_timeout: 10m
        script: |
          cd xfluencer/influencer-marketplace
          git pull
          cd src/ui
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 20
          npm cache clean -f
          npm install
          npm run build 
          sudo systemctl restart nginx
          pm2 stop marketplace
          pm2 start npm --name marketplace -- start
          
    - name: Remove Github Actions IP from security group
      if: always()
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
